# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f45252623152ce4bfb7478e58820f4c9b1d908cded7b6c99756e95ccdc97512d0b9402b4870f30795062e1ed63c8c2a4df2c1888047d80ad8994ba38242f36

test:
  secret_key_base: 7f1aff5a1f9cb96d4406c6eaf829d932c6984d471799928e4e679fae9453fa37568927371817219026f87435e31a381ee50a700037eaabd62fe8584e8c67f593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
